#!/bin/sh
set -eu

STUDIO_REPO=$1
UV_BIN=$2
ROBOTD_SOCKET=$3
BODY_PORT=$4
STUDIO_PORT=$5
RUNTIME_DIR=$6
cd "$STUDIO_REPO"

export MICRODUCK_REPO=../microduck
export MICRODUCK_RL_REPO=../microduck_rl
export MICRODUCK_ROBOTD_SOCKET="$ROBOTD_SOCKET"
export MICRODUCK_BODY_HOST=127.0.0.1
export MICRODUCK_BODY_PORT="$BODY_PORT"
export MICRODUCK_STUDIO_HOST=127.0.0.1
export MICRODUCK_STUDIO_PORT="$STUDIO_PORT"
export MICRODUCK_STUDIO_ENABLE_JOBS=false
export MICRODUCK_STUDIO_RUNTIME="$RUNTIME_DIR"

exec "$UV_BIN" run microduck-studio
